config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :albums
    resources :categories
    resources :events
    resources :instruments
    resources :news_items
    resources :orders
    resources :order_items
    resources :songs

    root to: "albums#index"
  end

  resources :instruments

  resource :order, only: [:show, :update]
  resource :address, only: [:new, :create]
  resource :payment, only: [:new, :create]
  resources :order_items

  get 'categories/index'

  get 'albums/songs'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'landing#index'

  get '/performance', to: 'pages#performance'
  get '/press',       to: 'pages#press'
  get '/contact',     to: 'messages#new'
  get '/press',       to: 'pages#press'
  get '/bio',         to: 'pages#bio'

  # Performances
  get '/performance/assemblies', to: 'pages#assemblies'
  get '/performance/residencies', to: 'pages#residencies'
  get '/performance/preschool', to: 'pages#preschool'
  get '/performance/church', to: 'pages#church'
  get '/performance/library', to: 'pages#library'
  get '/performance/concerts', to: 'pages#concerts'
  get '/performance/chris-and-jack', to: 'pages#chris_jack'

  resources :messages, only: [:new, :create]
  resources :albums, only: [:show, :index] do
    resources :songs, only: [:show]
  end

  get '/recordings', to: 'categories#index'
  get '/recordings/*uri', to: 'pages#album_redirect'
  get '/store/product/*uri', to: 'pages#instrument_redirect'
  get '/otherstuff', to: 'pages#otherstuff'
  get '/store/*uri', to: 'pages#maintenance'
  get '/calendar', to: 'pages#maintenance'
  get '/news', to: 'news_items#index'

  if ENV['ENABLE_STORE'] == 'true'
    get '/store', to: 'store#index'
  else
    get '/store', to: 'pages#maintenance'
  end

  post '/api/shipping', to: 'shipping#index'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items

  def cost_breakdown
    @cost_breakdown ||= compute_cost_breakdown
  end

  protected

  def compute_cost_breakdown
    limberjack = Instrument.find_by(slug: 'limberjack')

    limberjack_items = 0
    regular_items = 0
    subtotal = 0

    self.order_items.each do |oi|
      # Update counters for shipping costs
      if limberjack && limberjack.sku == oi.stripe_sku
        limberjack_items += oi.quantity.to_i
      else
        regular_items += oi.quantity.to_i
      end
      subtotal += oi.cost
    end

    ret = OpenStruct.new
    ret.subtotal = subtotal
    ret.shipping_cost = calculate_shipping(limberjack_items, regular_items)
    ret.total = ret.subtotal + ret.shipping_cost
    ret
  end

  def calculate_shipping(limberjacks, others)
    return 0 if limberjacks + others == 0
    if limberjacks > 0
      fee = 4
    else
      fee = 2
    end

    fee += (limberjacks * 2)
    fee += others
    return fee * 100 # shipping fee in pennies
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Order.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Order.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order
  def show
    # Display cart
  end

  def update
    # Update cart
  end
end

app/views/orders/_quantity_form.html.haml
= form_for(order_item, html: { class: 'cart-quantity-form'}) do |f|
  = f.number_field :quantity
  = f.submit 'update amount'
&nbsp;
&nbsp;
&nbsp;
%small
  = link_to 'Remove', order_item_path(order_item), method: :delete

app/views/orders/show.html.haml
%h1 Shopping Cart

- if @order.order_items.count == 0
  %p
    Your shopping cart is currently empty.  You can shop for merchandise in the
    <a href="/store/">store</a>.
- else
  %h2 Your Cart
  %table#shopping-cart
    %tr
      %th Quantity
      %th Item
      %th Price
      %th{ align: 'center' } Total
    - @order.order_items.each do |oi|
      %tr
        %td{ align: 'center' }
          = render 'quantity_form', order_item: oi
        %td
          = link_to oi.item_model.name, cart_item_uri(oi)
        %td{ align: 'center' }
          = format_pennies(oi.item_model.price_in_pennies)
        %td{ align: 'center'}
          = format_pennies(oi.item_model.price_in_pennies * oi.quantity)
  = link_to 'Check out', new_address_path, class: 'btn'
  &nbsp;
  &nbsp;
  &nbsp;
  = link_to 'Back to shopping', '/store'